### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by dodola** [moduth/blockcanary#10]
hi，感觉这种方法应对ANR的情况比较合适，但应对界面卡顿的情况还是不太合适，造成界面卡顿的时间片粒度太小了。是否可以重新开一个用Choreographer计算frame的skip数来判断类似滑动界面的卡顿

**Comment by markzhai** [comment]
用Choreographer计算frame的skip数来判断卡顿是合适的，但是那样一来就很难去获得可以追朔卡顿原因的信息

**Comment by dodola** [comment]
@markzhai 嗯，我用的方法是在skip count >10的时候拿取Debug的Method Trace文件 到skip count ==0时停止trace，然后用这段trace文件去分析，额。。。

**Comment by dodola** [comment]
@markzhai  还有个情况，比如在我的项目中也会用到 getMainLooper().setMessageLogging(null); 这个方法，会跟你的框架冲突，你们在Readme里标注一下吧，不要覆盖了mainlooper的messagelog，否则就无效了

**Comment by markzhai** [comment]
@dodola 恩。。。有道理

**Comment by markzhai** [comment]
@dodola 你那样拿到的trace文件分析起来怎么样？可以有效快速找到问题吗？

**Comment by dodola** [comment]
@markzhai 效果还行，trace有个好处就是可以看到每个方法的cpu time，更加直接一些，但是用起来不是很方便，每次都需要从手机里拷贝出来
