### ISSUE TITLE
can u provide a BlockCanaryContextAdapter?

### ISSUE THREAD

**Issue by JiangDaYa0** [moduth/blockcanary#13]
RT.

**Comment by markzhai** [comment]
What do you mean by BlockCanaryContextAdapter

**Comment by JiangDaYa0** [comment]
不需要实现所有方法啊~~

**Comment by markzhai** [comment]
I see, will add in next version.

**Comment by markzhai** [comment]
done in https://github.com/moduth/blockcanary/commit/b69cbb29c608819eec710508f164d82b850efdeb
