### ISSUE TITLE
The license and the credit of leakcanary

### ISSUE THREAD

**Issue by liaohuqiu** [moduth/blockcanary#17]
I saw you use a lot of UI of [`leakcanary`](https://github.com/square/leakcanary), probably some of the content of the `README`. And leakcanary is inder Apache 2.0. 

You did not use that license, and give any credit neither.

**Comment by markzhai** [comment]
I use that license (https://github.com/moduth/blockcanary/blob/master/LICENSE), just miss them in java files, will add soon later. @liaohuqiu

**Comment by markzhai** [comment]
@liaohuqiu have added license in all java files, please check

**Comment by liaohuqiu** [comment]
Great! :beers:
