### ISSUE TITLE
读取log时，数组越界导致crash

### ISSUE THREAD

**Issue by chenlongkk** [moduth/blockcanary#18]
配置BlockCanaryContext时，如果某个log字段为“”，那么Block newInstance(File )方法会抛出异常，跳过读取后续的字段。在DisplayBlockActivity 299行，block.timeStart为空，导致crash

**Comment by markzhai** [comment]
谢谢，应该是个bug，我确认一下

**Comment by markzhai** [comment]
fixed https://github.com/moduth/blockcanary/commit/5c29e1ceaeeaa0429b198b9cfd99ee14f759a0c2
