### ISSUE TITLE
堆栈信息无法折叠展开

### ISSUE THREAD

**Issue by oubeichen** [moduth/blockcanary#19]
查看Log信息的界面里，上面的CPU、Memory等三项信息可以折叠展开。但最后一项堆栈信息（可能有多次堆栈信息）不行。只会在最后面加上一句“blocked”。

这是BUG还是我的使用方式有误？

除此之外这个包非常好用，谢谢！

**Comment by markzhai** [comment]
你好，在判断如何折叠堆栈信息的时候，有过几次变更

- 前期有考虑过根据黑名单如''android.*", “java.*” 来过滤系统方法，取第一个非系统方法作为默认非折叠，但后来发现仍然不够直观，因为无法涵盖所有系统方法。
- 后来我改成了根据package name去过滤，结果又出现有时候的堆栈跟PackageInfo里的packageName毫无关系的问题
- 最后变成了现在这样，根据进程名去过滤，找到第一行以进程名打头的堆栈调用。

你可以检查一下是否你的包名和进程名是完全不一致的，也欢迎提供意见，这一块我觉得有改善空间。

**Comment by oubeichen** [comment]
对，我们为了内部测试方便，定义了debug版，beta版，release版等。这些版本的processName和package name会加上后缀，与堆栈信息中的类所在包名不完全一致。
刚才检查BlockDetailAdapter.java也发现了。
我觉得可以在BlockCanaryContext让用户指定自己的类所在的包名。如果不指定则使用默认（packageName，processName或者按行数折叠）。

**Comment by markzhai** [comment]
@oubeichen 说的有道理，可以让用户优先指定，这个逻辑可以加一下
