### ISSUE TITLE
找不到BlockCanary类

### ISSUE THREAD

**Issue by Ztiany** [moduth/blockcanary#22]
你好，按照文档添加了下面依赖

        compile 'com.github.moduth:blockcanary-android:1.1.0'
        debugCompile 'com.github.moduth:blockcanary-ui:1.1.0'

但是在工程中找不到BlockCanary类，有没有可能和其他的库有冲突？

以下是我项目的依赖

      dependencies {
           def AndroidSupportVersion = "23.1.1"
           compile fileTree(dir: 'libs', include: ['*.jar'])
           testCompile 'junit:junit:4.12'
           compile "com.android.support:recyclerview-v7:$AndroidSupportVersion"
           compile "com.android.support:appcompat-v7:$AndroidSupportVersion"
           compile "com.android.support:design:$AndroidSupportVersion"
           compile "com.android.support:cardview-v7:$AndroidSupportVersion"

           compile "com.android.support:percent:$AndroidSupportVersion" 
           compile 'com.google.code.gson:gson:2.5'
           compile 'eu.the4thfloor.volley:com.android.volley:2015.05.28'
           compile 'com.github.bumptech.glide:glide:3.6.1'
   
           debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3.1'
           releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3.1'
   
           compile 'com.github.moduth:blockcanary-android:1.1.0'
           debugCompile 'com.github.moduth:blockcanary-ui:1.1.0'

          
           compile project(':refreshLibrary')
           compile project(':baselibrary')
           compile project(':ThirdLibrary')
           compile project(':zxinglibrary')
}

**Comment by markzhai** [comment]
@Ztiany 你好，我新建了一个项目试了一下，是没有问题的，你看看External Libraries里面，有没有blockcanary的包呢

**Comment by zzz40500** [comment]
run 一下,再试试看有没有.

**Comment by markzhai** [comment]
repositories {
    mavenCentral()
}

在root的jcenter那里加一下mavenCentral看看，可能是mavenCentral还没有同步到jcenter

**Comment by Ztiany** [comment]
好的，明天试试，thx

**Comment by markzhai** [comment]
请看README里面1.1.3的用法，我这里测试没有问题了

**Comment by Ztiany** [comment]
可以了，即使找不到相关类，run一下就出来了。
