### ISSUE TITLE
com.github.moduth:blockcanary-ui:1.1.0 AndroidManifest.xml不要允许备份吧

### ISSUE THREAD

**Issue by JakeWoki** [moduth/blockcanary#23]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.github.moduth.blockcanary">

    <application android:allowBackup="true"
        android:label="@string/app_name">
        <activity
            android:name=".ui.DisplayBlockActivity"
            android:icon="@drawable/block_canary_icon"
            android:label="@string/display_activity_label"
            android:taskAffinity="com.github.moduth.blockcanary"
            android:theme="@style/block_canary_BlockCanary.Base">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

    </application>

</manifest>
---
android:allowBackup="false"

**Comment by markzhai** [comment]
有道理，我改一下
