### ISSUE TITLE
Error:Failed to resolve: blockcanary:blockcanary-core:unspecified

### ISSUE THREAD

**Issue by JakeWoki** [moduth/blockcanary#24]
compile 'com.github.moduth:blockcanary-android:1.1.1'

**Comment by markzhai** [comment]
repositories {
    mavenCentral()
}

在root的jcenter那里加一下mavenCentral看看，可能是mavenCentral还没有同步到jcenter

**Comment by markzhai** [comment]
请看README里面1.1.3的用法，应该没有问题了
