### ISSUE TITLE
1.1.0打包release版本出错

### ISSUE THREAD

**Issue by jp1017** [moduth/blockcanary#25]
```gradle
dependencies {
    compile 'com.github.moduth:blockcanary-android:1.1.0'
    debugCompile 'com.github.moduth:blockcanary-ui:1.1.0'
}
```

debug版本正常

然，release：

![2016-01-26 08-53-13](https://cloud.githubusercontent.com/assets/7868514/12569547/d351f020-c40a-11e5-98f7-bdd77a612c40.png)

**Comment by markzhai** [comment]
请看README里面1.1.3的用法，应该没有问题了

**Comment by jp1017** [comment]
1.1.3版本，release可以了

但是debug版本为什么去掉通知？

**Comment by markzhai** [comment]
现在分成了3个库，链式依赖：
blockcanary-ui
blockcanary-android
blockcanary-core
需要卡顿通知和ui的用第一个，只需要记录log来分析的用第二个，希望release包什么都不打的用blockcanary-no-op

**Comment by jp1017** [comment]
三个库，怎么还有个blockcanary-no-op，好乱

**Comment by markzhai** [comment]
3个是链式的，只需要引入任意需要的1个就行了

**Comment by jp1017** [comment]
好的，谢谢了
