### ISSUE TITLE
Could you please comment in English?

### ISSUE THREAD

**Issue by Rainer-Lang** [moduth/blockcanary#33]
It's much harder to understand the sample app if the comments are in "not" English. 
Please could you use English? Thanks. :)

**Comment by snowdream** [comment]
Good Idea

**Comment by markzhai** [comment]
You are right

**Comment by markzhai** [comment]
@Rainer-Lang  Hey there, all comments have been updated to English, please check. Thanks

**Comment by markzhai** [comment]
Done in https://github.com/moduth/blockcanary/commit/898368a9c89136b28a233971ccbef4270b82a8d1

**Comment by Rainer-Lang** [comment]
@markzhai Thanks a lot. :)
I close this issue, OK?
