### ISSUE TITLE
居然被和谐了。。

### ISSUE THREAD

**Issue by MIkeeJY** [moduth/blockcanary#55]

**Comment by ahkkfh** [comment]
居然被删除了，什么情况

**Comment by MIkeeJY** [comment]
@ahkkfh  仓库的代码应该还能用。。。

**Comment by markzhai** [comment]
@MIkeeJY @ahkkfh 风头比较紧...避避风头...我在自己的github fork了一份...这边等风头过了再恢复 https://github.com/markzhai/blockcanary/

**Comment by MIkeeJY** [comment]
@markzhai 3Q

**Comment by xiaolongyuan** [comment]
为什么？？

**Comment by youxiachai** [comment]
@xiaolongyuan 看commit 好像跟阿里有关吧?

**Comment by markzhai** [comment]
@youxiachai @xiaolongyuan 
因为这个项目最早我在阿里内部开源的，虽然没有别人帮忙协助写过任何代码。。。现在阿里联系来说内部开源的外面不能随便开源，让我删了
