### ISSUE TITLE
找不到start()方法

### ISSUE THREAD

**Issue by zhonghanwen** [moduth/blockcanary#9]
![image](https://cloud.githubusercontent.com/assets/12220537/12443584/c846c208-bf93-11e5-878f-dfebe231d2b1.png)

**Comment by markzhai** [comment]
请提供你的build.gradle引用BlockCanary方法

**Comment by nimengbo** [comment]
@zhonghanwen  你的cradle 是不是2个库都写了compile

**Comment by zhonghanwen** [comment]
![image](https://cloud.githubusercontent.com/assets/12220537/12443642/40e1dfa4-bf94-11e5-9916-d735b5038ca0.png)

**Comment by zhonghanwen** [comment]
@markzhai 
![image](https://cloud.githubusercontent.com/assets/12220537/12443716/e2fe7e46-bf94-11e5-9127-3843053abb02.png) 不是这样么？

**Comment by markzhai** [comment]
你的buildType是debug吗，可以尝试直接用
compile 'com.github.moduth:blockcanary:1.0.0'

**Comment by zhonghanwen** [comment]
@markzhai 
![image](https://cloud.githubusercontent.com/assets/12220537/12443766/49787992-bf95-11e5-88ac-fa04306cdad2.png) 难度是false的原因吗？

**Comment by markzhai** [comment]
@zhonghanwen 我知道了，你用到了releaseCompile，但是no-op包里的方法名忘记改了，我修正一下，你可以先直接用compile 'com.github.moduth:blockcanary:1.0.0'

**Comment by zhonghanwen** [comment]
直接用compile 'com.github.moduth:blockcanary:1.0.0'就可以了，谢谢 @markzhai

**Comment by markzhai** [comment]
fixed in 1.0.1
